### ISSUE TITLE
 EndToEndTest.BasicFunctionalityTest doesn't pass.

### ISSUE THREAD

**Issue by icecog** [Azure/azure-iot-protocol-gateway#7]
Hey, Im having problems with the EndToEndTest.BasicFunctionalityTest in azure-iot-protocol-gateway/ProtocolGateway - it doesnt pass.

I've input my iot hub connection string and I can see that the devices get provisioned, but no messages are ever received by the hub according the the Azure portal.

I've opened ports 5672 and 8883 on my computer.
I cant seem to get any closer to a reason for the failure - any ideas for what could be wrong?

Error:

Test Name:	Microsoft.Azure.Devices.ProtocolGateway.Tests.EndToEndTests.BasicFunctionalityTest
Test FullName:	Microsoft.Azure.Devices.ProtocolGateway.Tests.EndToEndTests.BasicFunctionalityTest
Test Source:	C:\Users\tomsig\Source\Repos\azure-iot-protocol-gateway\test\ProtocolGateway.Tests\EndToEndTests.cs : line 179
Test Outcome:	Failed
Test Duration:	0:05:21,397

Result StackTrace:	
at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout)
   at Microsoft.Azure.Devices.Gateway.Tests.Extensions.TaskExtensions.<WhenSome>d__0.MoveNext() in C:\Users\tomsig\Source\Repos\azure-iot-protocol-gateway\test\ProtocolGateway.Tests\Extensions\TaskExtensions.cs:line 19
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at Microsoft.Azure.Devices.ProtocolGateway.Tests.EndToEndTests.<BasicFunctionalityTest>d__30.MoveNext() in C:\Users\tomsig\Source\Repos\azure-iot-protocol-gateway\test\ProtocolGateway.Tests\EndToEndTests.cs:line 285
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
----- Inner Stack Trace -----
   at Microsoft.Azure.Devices.ProtocolGateway.Tests.EndToEndTests.<>c.<<BasicFunctionalityTest>b__30_9>d.MoveNext() in C:\Users\tomsig\Source\Repos\azure-iot-protocol-gateway\test\ProtocolGateway.Tests\EndToEndTests.cs:line 282
Result Message:	
System.AggregateException : One or more errors occurred.
---- System.TimeoutException : Test has timed out.

**Comment by nayato** [comment]
If you're running test without specifying standalone protocol gateway address, test output should have more details. Likely cause: protocol gateway has to be started as admin in order to provision its performance counters. Try running VS as admin or if you're using standalone protocol gateway - run that process as admin.

**Comment by nayato** [comment]
@icecog have you tried to verify my suspicion?

**Comment by icecog** [comment]
Terribly sorry Max, must have missed the first mail!

Yes, that did fix that right up! Thank you! 

Such a simple problem, any way to detect this and provide a warning or a test for to bad devs like me?

**Comment by palashsharma25** [comment]
Hi ,
I am getting the following error even after giving the address "127.0.0.1" and runing as administrator,Please help in resolving:
Test Name:	Microsoft.Azure.Devices.ProtocolGateway.Tests.EndToEndTests.BasicFunctionalityTest
Test FullName:	Microsoft.Azure.Devices.ProtocolGateway.Tests.EndToEndTests.BasicFunctionalityTest
Test Source:	G:\azure-iot-protocol-gateway-master\test\ProtocolGateway.Tests\EndToEndTests.cs : line 179
Test Outcome:	Failed
Test Duration:	0:05:17.968

Result StackTrace:	
at Microsoft.Azure.Devices.ProtocolGateway.Tests.Extensions.TaskExtensions.<WithTimeoutInternal>d__1.MoveNext() in G:\azure-iot-protocol-gateway-master\test\ProtocolGateway.Tests\Extensions\TaskExtensions.cs:line 34
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at Microsoft.Azure.Devices.ProtocolGateway.Tests.EndToEndTests.<BasicFunctionalityTest>d__26.MoveNext() in G:\azure-iot-protocol-gateway-master\test\ProtocolGateway.Tests\EndToEndTests.cs:line 273
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
Result Message:	System.TimeoutException : The operation has timed out.
